import re


# Heuristic patterns for commands that are almost never intentional in a
# CI/build step and would cause serious, hard-to-undo damage if run by
# mistake (a typo, a copy-paste error). This is a safety net against
# self-inflicted accidents, not a security sandbox: --ci-command is
# supplied by the person running Olive, not generated by a model, and
# these patterns can't catch everything destructive -- just the common,
# recognizable ones (spec sec 38's "dangerous-command detection").
_DANGEROUS_PATTERNS = [
    # rm -rf targeting root, home, or a wildcard-only path
    re.compile(r"\brm\s+(-\w*r\w*f\w*|-\w*f\w*r\w*)\s+(/|~|\*|/\*|\$HOME\b)", re.IGNORECASE),
    # PowerShell Remove-Item -Recurse -Force targeting a drive root or $HOME
    re.compile(
        r"\bRemove-Item\b.*-Recurse\b.*-Force\b.*"
        r"([A-Za-z]:\\{1,2}(?:\s|$)|[A-Za-z]:/(?:\s|$)|\$HOME\b|~\\?(?:\s|$))",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bRemove-Item\b.*-Force\b.*-Recurse\b.*"
        r"([A-Za-z]:\\{1,2}(?:\s|$)|[A-Za-z]:/(?:\s|$)|\$HOME\b|~\\?(?:\s|$))",
        re.IGNORECASE,
    ),
    # del /s /q targeting a drive root
    re.compile(r"\bdel\s+/s\s+/q\s+[A-Za-z]:\\?\s*$", re.IGNORECASE),
    # Whole-disk format / filesystem creation
    re.compile(r"\bformat\s+[A-Za-z]:", re.IGNORECASE),
    re.compile(r"\bmkfs(\.\w+)?\b", re.IGNORECASE),
    # Raw disk writes
    re.compile(r"\bdd\s+.*\bof=/dev/", re.IGNORECASE),
    # Classic bash fork bomb
    re.compile(r":\(\)\s*\{\s*:\s*\|\s*:\s*&\s*\}\s*;\s*:"),
]


def is_dangerous_command(command: str) -> str | None:
    """Return a human-readable reason if `command` matches a known
    destructive pattern, else None. A best-effort heuristic check, not a
    guarantee -- see module docstring.
    """

    for pattern in _DANGEROUS_PATTERNS:
        if pattern.search(command):
            return (
                "Command matches a known destructive pattern "
                f"(recursive/whole-disk deletion or similar): {command!r}"
            )

    return None
