from dataclasses import dataclass, field

from olive.state.task import Task


@dataclass
class TaskGraph:
    """Internal dependency graph generated by Olive Framework."""

    tasks: list[Task] = field(default_factory=list)

    def get_task(self, task_id: str) -> Task:
        for task in self.tasks:
            if task.id == task_id:
                return task

        raise KeyError(f"Task not found: {task_id}")

    def task_ids(self) -> set[str]:
        return {task.id for task in self.tasks}

    def ready_tasks(self, completed: set[str]) -> list[Task]:
        """Return tasks whose dependencies have all been completed."""

        return [
            task
            for task in self.tasks
            if task.id not in completed
            and all(
                dependency in completed
                for dependency in task.dependencies
            )
        ]

    def validate(self) -> None:
        """Validate the dependency graph."""

        self._validate_unique_ids()
        self._validate_dependencies_exist()
        self._validate_no_self_dependencies()
        self._validate_no_cycles()

    def _validate_unique_ids(self) -> None:
        ids = [task.id for task in self.tasks]

        if len(ids) != len(set(ids)):
            raise ValueError(
                "Task graph contains duplicate task IDs"
            )

    def _validate_dependencies_exist(self) -> None:
        ids = self.task_ids()

        for task in self.tasks:
            for dependency in task.dependencies:
                if dependency not in ids:
                    raise ValueError(
                        f"{task.id} depends on unknown task "
                        f"{dependency}"
                    )

    def _validate_no_self_dependencies(self) -> None:
        for task in self.tasks:
            if task.id in task.dependencies:
                raise ValueError(
                    f"{task.id} cannot depend on itself"
                )

    def _validate_no_cycles(self) -> None:
        graph = {
            task.id: task.dependencies
            for task in self.tasks
        }

        visiting = set()
        visited = set()

        def visit(task_id: str) -> None:
            if task_id in visiting:
                raise ValueError(
                    "Task graph contains a circular dependency"
                )

            if task_id in visited:
                return

            visiting.add(task_id)

            for dependency in graph[task_id]:
                visit(dependency)

            visiting.remove(task_id)
            visited.add(task_id)

        for task_id in graph:
            visit(task_id)
